python3 test_multiDataLoader_metric3d.py  \
    --data_name NYU \
    --dir_data /scratchdata/nyudepthv2 \
    --model_name depth_prompt_main \
    --pretrain /scratchdata/pretrained/OURS/Depthprompting_depthformer_nyu.tar \
    --prop_kernel 9 \
    --conf_prop \
    --prop_time 18 \
    --patch_height 480 \
    --patch_width 640 \
    --nyu_val_samples 1000,500,200,100,5,1 \
    --init_scailing \
    --gpu 0